[package]
name = "tokenizer-japanese"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "0.2.91", features = ["serde"] }
serde_json = "1.0.113"
lindera-tokenizer = { version = "0.28.0", features = ["ipadic"] }
lindera-core = "0.28.0"
lindera-dictionary = "0.28.0"

[lib]
crate-type = ["cdylib", "rlib"]
