[package]
name = "tokenizer-mandarin"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "0.2.91", features = ["serde"] }
serde_json = "1.0.113"
jieba-rs = "0.6.8"

[lib]
crate-type = ["cdylib", "rlib"]
